cabal-version:      2.4
name:               PayRules
version:            0.1.0.0
synopsis:           A pure, typed authorization rules engine for payment transactions.
description:
  Evaluates a transaction against a pipeline of composable, pure authorization
  rules and returns an approve/decline decision together with a reasoning trail
  (which rule fired and why).
homepage:           https://github.com/HxrshRaj/PayRules
license:            MIT
license-file:       LICENSE
author:             Harsh Raj
maintainer:         hraj15709@gmail.com
build-type:         Simple
extra-doc-files:    README.md
tested-with:        GHC ==9.6.6

common lang
  default-language:   Haskell2010
  ghc-options:
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wredundant-constraints
    -Wno-name-shadowing

library
  import:           lang
  hs-source-dirs:   src
  exposed-modules:
      PayRules.Money
      PayRules.Types
      PayRules.Rules
      PayRules.Engine
      PayRules.Sample
      PayRules.Wire
  build-depends:
      base        >=4.14 && <5
    , aeson       >=2.0  && <2.3
    , containers  >=0.6  && <0.8
    , text        >=1.2  && <3
    , time        >=1.9  && <2

executable payrules
  import:           lang
  hs-source-dirs:   app
  main-is:          Main.hs
  ghc-options:      -threaded -rtsopts -with-rtsopts=-N
  build-depends:
      base
    , text
    , time
    , PayRules

executable payrules-server
  import:           lang
  hs-source-dirs:   server
  main-is:          Main.hs
  ghc-options:      -threaded -rtsopts -with-rtsopts=-N
  build-depends:
      base
    , aeson
    , text
    , time
    , servant         >=0.19 && <0.21
    , servant-server   >=0.19 && <0.21
    , wai              >=3.2  && <3.3
    , warp             >=3.3  && <3.5
    , PayRules

test-suite payrules-test
  import:           lang
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Spec.hs
  other-modules:    PayRules.Gen
  build-depends:
      base
    , aeson
    , containers
    , text
    , time
    , QuickCheck  >=2.14 && <2.16
    , PayRules
